### ISSUE TITLE
[CBLRemoteRequest description] Crash - while writing error data to logger

### ISSUE THREAD

**Issue by msanilkumar2020** [couchbase/couchbase-lite-ios#1541]
Thread 17 name:  Dispatch queue: NSOperationQueue 0x17063ec00 :: NSOperation 0x17085ffb0 (QOS: DEFAULT)
Thread 17 Crashed:
0   CFNetwork                     	0x0000000186da0830 0x186d0c000 + 608304
1   CFNetwork                     	0x0000000186da0824 0x186d0c000 + 608292
2   CFNetwork                     	0x0000000186ee7f80 0x186d0c000 + 1949568
3   xxxxxx                 	0x000000010072fe08 -[CBLRemoteRequest description] (CBLRemoteRequest.m:173)
4   Foundation                    	0x0000000187118b14 0x187117000 + 6932
5   CoreFoundation                	0x00000001866ce23c 0x1865dd000 + 987708
6   CoreFoundation                	0x00000001866cc2c8 0x1865dd000 + 979656
7    xxxxxx                   	0x0000000100725b3c _Logv (MYLogging.m:225)
8    xxxxxx                  	0x0000000100725c9c MYLogTo (MYLogging.m:290)
9   xxxxxx                   	0x000000010075d040 -[CBLRemoteSession URLSession:task:didCompleteWithError:] (CBLRemoteSession.m:327)
10  CFNetwork                     	0x0000000186ed98e0 0x186d0c000 + 1890528
11  Foundation                    	0x00000001871fbfb0 0x187117000 + 937904
12  Foundation                    	0x0000000187140aa8 0x187117000 + 170664
13  Foundation                    	0x00000001871310a4 0x187117000 + 106660
14  Foundation                    	0x00000001871fe35c 0x187117000 + 947036
15  libdispatch.dylib             	0x00000001855961bc 0x185595000 + 4540
16  libdispatch.dylib             	0x00000001855a43dc 0x185595000 + 62428
17  libdispatch.dylib             	0x00000001855999a4 0x185595000 + 18852
18  libdispatch.dylib             	0x00000001855a634c 0x185595000 + 70476
19  libdispatch.dylib             	0x00000001855a60ac 0x185595000 + 69804
20  libsystem_pthread.dylib       	0x000000018579f2a0 0x18579e000 + 4768
21  libsystem_pthread.dylib       	0x000000018579ed8c 0x18579e000 + 3468

--------
* Version:   1.3.1
* Client OS: iOS 10

**Comment by pasin** [comment]
What is the cause of the crash?

**Comment by msanilkumar2020** [comment]
@pasin, this crash is not that frequent but occurring randomly during network transition.

Please find the below details on  crash type, today also i found the same crash stack.
Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000048
Termination Signal: Segmentation fault: 11
Termination Reason: Namespace SIGNAL, Code 0xb
Terminating Process: exc handler [0]
Triggered by Thread:  17

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000048
Termination Signal: Segmentation fault: 11
Termination Reason: Namespace SIGNAL, Code 0xb
Terminating Process: exc handler [0]
Triggered by Thread:  22

hread 22 name:  Dispatch queue: NSOperationQueue 0x174c3f240 :: NSOperation 0x17664aef0 (QOS: DEFAULT)
Thread 22 Crashed:
0   CFNetwork                     	0x0000000190fec830 0x190f58000 + 608304
1   CFNetwork                     	0x0000000190fec824 0x190f58000 + 608292
2   CFNetwork                     	0x0000000191133f80 0x190f58000 + 1949568
3   Push To Talk+                 	0x000000010076fe08 -[CBLRemoteRequest description] (CBLRemoteRequest.m:173)
4   Foundation                    	0x0000000191364b14 0x191363000 + 6932
5   CoreFoundation                	0x000000019091a23c 0x190829000 + 987708
6   CoreFoundation                	0x00000001909182c8 0x190829000 + 979656
7   xxxxxxxxxxxx                 	0x0000000100765b3c _Logv (MYLogging.m:225)
8  xxxxxxxxxxxx                 	0x0000000100765c9c MYLogTo (MYLogging.m:290)
9   xxxxxxxxxxxx                  	0x000000010079d040 -[CBLRemoteSession URLSession:task:didCompleteWithError:] (CBLRemoteSession.m:327)
10  CFNetwork                     	0x00000001911258e0 0x190f58000 + 1890528
11  Foundation                    	0x0000000191447fb0 0x191363000 + 937904
12  Foundation                    	0x000000019138caa8 0x191363000 + 170664
13  Foundation                    	0x000000019137d0a4 0x191363000 + 106660
14  Foundation                    	0x000000019144a35c 0x191363000 + 947036
15  libdispatch.dylib             	0x000000018f7e21bc 0x18f7e1000 + 4540
16  libdispatch.dylib             	0x000000018f7f03dc 0x18f7e1000 + 62428
17  libdispatch.dylib             	0x000000018f7e59a4 0x18f7e1000 + 18852
18  libdispatch.dylib             	0x000000018f7f234c 0x18f7e1000 + 70476
19  libdispatch.dylib             	0x000000018f7f20ac 0x18f7e1000 + 69804
20  libsystem_pthread.dylib       	0x000000018f9eb2a0 0x18f9ea000 + 4768
21  libsystem_pthread.dylib       	0x000000018f9ead8c 0x18f9ea000 + 3468

**Comment by snej** [comment]
We can't figure out why this would happen, but it only occurs if RemoteRequest logging is enabled (since the crash happens inside of a LogTo call.) This logging shouldn't be enabled in normal use since it slows performance and can write a lot of stuff to the log file. So this seems like a low priority to fix.

**Comment by msanilkumar2020** [comment]
@snej , we have enabled logging in debugging build in production this will be disabled. This crash is occurring randomly during network transition. We can disable RemoteRequest logging, in this case we will miss the logs if some issue occurs.

**Comment by pasin** [comment]
Closed in https://github.com/couchbase/couchbase-lite-ios/commit/2bb369a1ddfd834f11e2ab2a5ef4ae9d7d335e15.

**Comment by pasin** [comment]
Fixed in https://github.com/couchbase/couchbase-lite-ios/commit/2bb369a1ddfd834f11e2ab2a5ef4ae9d7d335e15.

**Comment by msanilkumar2020** [comment]
@pasin , still we are getting this logger crash but the frequency is less.

Date/Time:           2017-04-13 17:32:10.6910 +0530
Launch Time:         2017-04-13 17:28:39.0000 +0530
OS Version:          iPhone OS 10.3 (14E5277a)
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x74636172
Termination Signal: Segmentation fault: 11
Termination Reason: Namespace SIGNAL, Code 0xb
Terminating Process: exc handler [0]
Triggered by Thread:  9

Thread 9 name:  Dispatch queue: NSOperationQueue 0xb1f8320 :: NSOperation 0xb0e5710 (QOS: DEFAULT)
Thread 9 Crashed:
0   CoreFoundation                	0x1b8031ca 0x1b801000 + 8650
1   CFNetwork                     	0x1beaac38 0x1be29000 + 531512
2   CFNetwork                     	0x1bfabce4 0x1be29000 + 1584356
3   APP_NAME             	0x00610be0 -[CBLRemoteRequest description] (CBLRemoteRequest.m:173)
4   Foundation                    	0x1c154396 0x1c152000 + 9110
5   CoreFoundation                	0x1b8c81f6 0x1b801000 + 815606
6   CoreFoundation                	0x1b8c5a66 0x1b801000 + 805478
7   Foundation                    	0x1c154338 0x1c152000 + 9016
8   Foundation                    	0x1c15a328 0x1c152000 + 33576
9   APP_NAME             	0x00607e26 _Logv (MYLogging.m:225)
10  APP_NAME             	0x00607f4c MYLogTo (MYLogging.m:290)
11  APP_NAME             	0x0063912e -[CBLRemoteSession URLSession:task:didCompleteWithError:] (CBLRemoteSession.m:332)
12  CFNetwork                     	0x1bf9ee4e 0x1be29000 + 1531470
13  Foundation                    	0x1c221ac0 0x1c152000 + 850624
14  Foundation                    	0x1c177aae 0x1c152000 + 154286
15  Foundation                    	0x1c169fa6 0x1c152000 + 98214
16  Foundation                    	0x1c223cf8 0x1c152000 + 859384
17  libdispatch.dylib             	0x1afd659c 0x1afc8000 + 58780
18  libdispatch.dylib             	0x1afccb70 0x1afc8000 + 19312
19  libdispatch.dylib             	0x1afd81b4 0x1afc8000 + 65972
20  libdispatch.dylib             	0x1afd800e 0x1afc8000 + 65550
21  libsystem_pthread.dylib       	0x1b17e8ec 0x1b17d000 + 6380
22  libsystem_pthread.dylib       	0x1b17e4cc 0x1b17d000 + 5324

**Comment by msanilkumar2020** [comment]
@pasin , still this issue is observed.

If we enable logs, we are getting this crash. As of now this issue is not fixed in 1.4 release.

**Comment by pasin** [comment]
@msanilkumar2020 Can you provide a full stacktrace with all threads? How do you capture the crash log? Would it be possible to make the crash log symbolicated completely?

**Comment by msanilkumar2020** [comment]
@pasin ,
 i have taken fix from branch now will test it for some time and will update you on this issue.
