### ISSUE TITLE
openDatabaseNamed failing with SQLite Code=23 "authorization denied" error

### ISSUE THREAD

**Issue by skela** [couchbase/couchbase-lite-ios#1612]
Been experiencing some issues for a few months now related to a very hard to reproduce issue causing my app to not behave properly. Was able to pin-point the issue today to the database failing to open due to an authorization denied SQLite 23 error: `Error Domain=SQLite Code=23 "authorization denied" UserInfo={NSLocalizedDescription=authorization denied}`

I've come across some older posts about it potentially being related to iOS file protection, but nothing conclusive came up so raising the issue here hoping I can get some help to work around it / avoid it.

I found a purported fix on [StackOverflow](http://stackoverflow.com/questions/35149668/ios-couchbase-lite-replication-error) that was supposed to fix it, by switching off the file protection, but the issue is still present. Although I'm not sure whether thats because the fileProtection options are only set when the database is first created or not, or whether the fileProtection stuff doesn't fix the issue anyway.

	fileprivate func createManager(_ queue: DispatchQueue) -> CBLManager?
	{
	    let writingOptions : NSData.WritingOptions = NSData.WritingOptions.noFileProtection
	    let options = CBLManagerOptions(readOnly:false,fileProtection:writingOptions)
	    
	    let cblpoptions = UnsafeMutablePointer<CBLManagerOptions>.allocate(capacity:1)
	    cblpoptions.initialize(to:options)
	    
	    if let mng = manager { return mng }
	    
	    do
	    {
	        let mng = try CBLManager(directory:CBLManager.defaultDirectory(),options:cblpoptions)
	        mng.dispatchQueue = queue
	        return mng
	    }
	    catch let error
	    {
	        log.error("Failed to create cb manager - \(error)")
	    }
	    return nil
	}

	fileprivate func createDatabase(_ syncGateway:String) -> CBLDatabase?
	{
	    let dbName = syncGateway.lastPathComponent
	    let options = CBLDatabaseOptions(); options.create = true
	    
	    if gateway != syncGateway
	    {
	        do
	        {
	            try db?.close()
	        }
	        catch
	        {
	            log.error("Failed to close cb database")
	        }
	        db = nil
	    }
	    
	    var database : CBLDatabase? = nil
	    
	    do
	    {
	        if db == nil { database = try manager!.openDatabaseNamed(dbName,with:options) }
	        else { database = db }
	    }
	    catch let error
	    {
	        log.error("Failed to open cb database - \(error)") // Failing here with "Failed to open cb database - Error Domain=SQLite Code=23 "authorization denied" UserInfo={NSLocalizedDescription=authorization denied}"
	    }
	    
	    return database
	}

--------
* Version: 1.3.1
* Client OS: 10.1.1

**Comment by pasin** [comment]
Changing the file protection issue was fixed in b50f92c945e3b45ab47b93f135a473a1701b090e. It will be in 1.4.0 release. Thanks.

**Comment by skela** [comment]
Any news on when 1.4.0 will be out? Can I try it out ?

**Comment by SergeyBulyno** [comment]
Hey, I Use version 1.4.0 via pods (objective c) and still receive 10-20k errors daily: "Domain: SQLite Code: 23 NSLocalizedDescription: authorization denied" when call method [[CBLManager sharedInstance] databaseNamed:nameConstant error:&error]; As I see this issue should be fixed in 1.4.0 but it's still reproduce. Can you help me ?

**Comment by PikaRules** [comment]
same than SergeyBulyno

**Comment by pasin** [comment]
@PikaRules Can you identify when the issue happen (e.g. when the app starts in the background due to notification)?

**Comment by udit1687** [comment]
Issue happen when app starts in the background due to location notification.
We have used couchbaselite version 1.4 and get location event using startMonitoringSignificantLocationChanges function of location manager delegate

**Comment by PikaRules** [comment]
It seems that it happens after opening the application from remote notification.  I had not been able to reproduce the issue but Im still getting notifications about this issue on crashlytics.

**Comment by PikaRules** [comment]
log

#0Crashed: com.splyza.spoch.couchDispatchQueue.userEXC_BREAKPOINT 0x0000000101fc3968 Raw Text
--
0 | libswiftCore.dylib | __hidden#23281_ line 134specialized _assertionFailure(StaticString, String, file : StaticString, line : UInt, flags : UInt32) -> Never
1 | libswiftCore.dylib | swift_unexpectedError + 354
2 | SpochCore | Couch.swift line 103Couch.(reset() -> ()).(closure #1)
3 | SpochCore | PushNotificationService.swift line 0thunk
4 | libdispatch.dylib | _dispatch_client_callout + 16
5 | libdispatch.dylib | _dispatch_queue_barrier_sync_invoke_and_complete + 56
6 | SpochCore | Couch.swift line 107Couch.reset() -> ()
7 | SpochCore | Couch.swift line 70static Couch.reset() -> ()
8 | SpochV2 | AppDelegate.swift line 14AppDelegate.(application(UIApplication, didFinishLaunchingWithOptions : [UIApplicationLaunchOptionsKey : Any]?) -> Bool).(closure #1)
9 | SpochCore | SessionManager.swift line 179SessionManager.restoreSession(completion : (SessionStatus) -> ()?) -> ()
10 | SpochV2 | AppDelegate.swift line 54specialized AppDelegate.application(UIApplication, didFinishLaunchingWithOptions : [UIApplicationLaunchOptionsKey : Any]?) -> Bool
11 | SpochV2 | AppDelegate.swift line 0@objc AppDelegate.application(UIApplication, didFinishLaunchingWithOptions : [UIApplicationLaunchOptionsKey : Any]?) -> Bool
12 | UIKit | -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 408
39 | UIKit | UIApplicationMain + 236
40 | SpochV2 | UploadCell.swift line 19main
41 | libdyld.dylib | start + 4

**Comment by PikaRules** [comment]
![screen shot 2018-07-25 at 18 51 49](https://user-images.githubusercontent.com/6718288/43193796-e55bdf06-903b-11e8-9364-9dc736109de8.png)

**Comment by PikaRules** [comment]
log:


\| | 03:51:21:821 (UTC) | \| | 12:51:21.810 INFO AppDelegate.application():28 - Launched with remote notification.
-- | -- | -- | --
2 | \| | 03:51:21:832 (UTC) | \| | 12:51:21.832 INFO AppDelegate.application():32 - Doing Couch initialization in didFinishLaunchingWithOptions.
3 | \| | 03:51:21:836 (UTC) | \| | 12:51:21.836 INFO CoreServices.initialize():38 - Creating database manager.
4 | \| | 03:51:21:891 (UTC) | \| | 12:51:21.890 INFO CoreServices.initialize():38 - Database manager created for type User. Directory protection: Optional(NSFileProtectionCompleteUntilFirstUserAuthentication).
5 | \| | 03:51:21:892 (UTC) | \| | 12:51:21.893 INFO CoreServices.initialize():38 - Creating database manager.
6 | \| | 03:51:21:901 (UTC) | \| | 12:51:21.901 INFO CoreServices.initialize():38 - Database manager created for type Shared. Directory protection: Optional(NSFileProtectionCompleteUntilFirstUserAuthentication).
7 | \| | 03:51:22:065 (UTC) | \| | 12:51:22.065 INFO AppDelegate.application():36 - Session restored with result ok.
8 | \| | 03:51:22:069 (UTC) | \| | 12:51:22.069 INFO CoreServices.initialize():38 - Opening database spoch-v1-aaaaaaaaaaaaaaaaaa

**Comment by PikaRules** [comment]
error:

`Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=SQLite Code=23 "authorization denied" UserInfo={NSLocalizedDescription=authorization denied}: file /BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-900.0.74.1/src/swift/stdlib/public/core/ErrorType.swift, line 181`

**Comment by PikaRules** [comment]
it happens on this line, when it tries to open the database:

` self.database = try? self.manager.databaseNamed(targetDBName)`

**Comment by snej** [comment]
@PikaRules, @udit1687, @SergeyBulyno: Are you aware of iOS File Protection, and have you set the CBLManager's file protection to a level that allows access while the device is locked?

**Comment by pasin** [comment]
@PikaRules You may try to change the file protection to None or CompleteUntilFirstUserAuthentication. For example, 

```Swift
var error: NSError?
let cbloptions = CBLManagerOptions(readOnly: false, fileProtection: NSDataWritingOptions.DataWritingFileProtectionNone)
let cblpoptions=UnsafeMutablePointer<CBLManagerOptions>.alloc(1)
cblpoptions.initialize(cbloptions)
manager = CBLManager(directory: CBLManager.defaultDirectory(), options: cblpoptions, error: &error)
```

**Comment by pasin** [comment]
Do you specifically set it to CBLManager or set to the Application Settings? If you change it to None to the CBLManager, will it help?

Note: CBL had a bug (probably in 1.3) that changing the fileProtection level doesn't affect some of the files. This has been fixed in the latest release. You may need to switch the fileProtection to None and then switch to CompleteUntilFirstUserAuthentication again to get around the issue.

**Comment by PikaRules** [comment]
yes I am setting the fileProptection option on the cblmanager.  I will try using None and then changing to  userFirstAu...  I will tell you later if it works. thanks.

**Comment by JuanPabloBoero** [comment]
@PikaRules did it work?

**Comment by leecommamichael** [comment]
@PikaRules did it work?
