### ISSUE TITLE
App crashes with !_docreader nil

### ISSUE THREAD

**Issue by SalmanZafar1105** [couchbase/couchbase-lite-ios#1796]
We are continuously getting this crash from random users, which we are unable to solve.

What do you think the problem is?
If it is related to a corrupted document, then how can we obtain the document id of the same.

Please help us to solve this crash as we are facing a major setback from our clients and this crash is really a showstopper, with plenty crashes in 1 month alone for a handful of users.

Crashlytics logs are attached.
[crash log.txt](https://github.com/couchbase/couchbase-lite-ios/files/1092122/crash.log.txt)
--------
* Version:   1.4.0
* Client OS: iOS - 10.2.1 and above
* Server:    Couchbase Server 4.6 and Sync Gateway version 1.4

**Comment by pasin** [comment]
This has been recently fixed in the master branch.

https://github.com/couchbase/couchbase-lite-ios/commit/1129e49c0b12cc0ac104e148a363554b31d6e940

**Comment by SalmanZafar1105** [comment]
Hi,

The issue still persists. I followed the exact procedure given in wiki pages to build the couchbaselite.framework from master branch. The application still crashes with the same error at the same line. 

Are we supposed to use the development build. We are archiving the build as continuousiOS.

Also, the version number is older than the one we were using, i.e. - we were using 1.4.0, and the version number in your framework is 1.3.1.

Crashlytics logs are attached.
[crash 2.txt](https://github.com/couchbase/couchbase-lite-ios/files/1097855/crash.2.txt)

We are suffering a lot, as we are getting continuous crash reports from everyone.

**Comment by pasin** [comment]
From the crash log, it doesn't seem you use the binary that contains the fix. Please make sure that you are using the binary built from the master branch. 

> Also, the version number is older than the one we were using, i.e. - we were using 1.4.0, and the version number in your framework is 1.3.1.

How do you get the version number?

**Comment by SalmanZafar1105** [comment]
We followed the steps given in the wiki files  - cloned the repository, checked out master branch, archived the build and copied the framework from inside the package.

The version number was inside the info.plist file in the framework.

**Comment by SalmanZafar1105** [comment]
We got it working. We were missing one step in the process 'git pull'. 
Thanks for your support.

**Comment by SalmanZafar1105** [comment]
I am still getting the same error. And we have the latest source.

Detailed logs - 
Sync: CBLRestPuller[http://****] Progress: 119 / 141
Sync: CBLRestPuller[http://****]: postProgressChanged (119/141, active=1 (batch=0, net=2), lastSeq=70691, online=1, error=(null))
Sync: CBLRestPuller[http://****]: no new remote revisions to fetch
Sync: *** CBLRestPuller[http://****]: END processInbox (lastSequence=70691)
Sync: CBLBulkDownloader[/****/_bulk_get]: Starting new document; ID="(null)"
Sync: CBLMultipartDocumentReader[_id="(null)"]: has attachments, multipart/related; boundary="aae47f0d74677fb9902bce12d53cd686d2791816534a366ccc0fd6d6fc36"
Sync: CBLMultipartDocumentReader[_id="-kids-14.png"]: Starting attachment #1...
CBLBulkDownloader[/****/_bulk_get]: Got error NSURLError[-1005, "The network connection was lost.", <http://***/_bulk_get?revs=true&attachments=true>]<--CFCFNetworkError[-1005]
*** ASSERTION FAILED: !_docReader
*** Assertion failure in -[CBLBulkDownloader startedPart:](), /Users/jenkins/jenkins/workspace/couchbase-lite-ios-builds@2/couchbase-lite-ios-enterprise/Source/CBLBulkDownloader.m:153
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '!_docReader'
*** First throw call stack:
(0x1861f91b8 0x184c3055c 0x1861f908c 0x186cb1098 0x101556784 0x10154cd48 0x10150fd4c 0x10154cac4 0x10150bb50 0x1015374b8 0x186d0d048 0x1861a6b5c 0x1861a64a4 0x1861a40a4 0x1860d22b8 0x186c0f26c 0x1014eeb4c 0x186d0ce68 0x18528d850 0x18528d760 0x18528ad94)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by pasin** [comment]
Please provide the full symbolicated crash log.
