### ISSUE TITLE
2.0 : Web Socket Warning and Sync Timeout Error

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-ios#1822]
From the Todo test fest, after leaving the app idle (without doing anything) for some time, I have seen the following in the log. Note that the replicator seems to be working even with the warning and error messages.

```
2017-07-14 13:21:56.911159-0700 Todo[2187:571196] CouchbaseLite WS WARNING: {1}--> blip:ec2-54-84-159-40.compute-1.amazonaws.com:4984/todo/_blipsync
2017-07-14 13:21:56.911939-0700 Todo[2187:571196] CouchbaseLite WS WARNING: {1} Unexpected or unclean socket disconnect! (reason=errno, code=60)
2017-07-14 13:21:56.915196-0700 Todo[2187:571196] CouchbaseLite  Info: ~BLIPIO: Max outbox depth was 1, avg 1.00
2017-07-14 13:21:56.916629-0700 Todo[2187:571853] CouchbaseLite Sync ERROR: {1}--> Repl->blip:ec2-54-84-159-40.compute-1.amazonaws.com:4984/todo/_blipsync
2017-07-14 13:21:56.917822-0700 Todo[2187:571853] CouchbaseLite Sync ERROR: {1} Got LiteCore error: Operation timed out (2/60)
2017-07-14 13:21:56.940202-0700 Todo[2187:570734] [Todo] Replicator: IDLE 0/0, error: Error Domain=NSPOSIXErrorDomain Code=60 "Operation timed out" UserInfo={NSLocalizedDescription=Operation timed out}
2017-07-14 13:21:59.076176-0700 Todo[2187:570734] [Todo] Replicator: BUSY 0/0, error: (null)
2017-07-14 13:21:59.347961-0700 Todo[2187:571196] <CBLHTTPLogic: 0x170089650>: Auth challenge; credential = <NSURLCredential: 0x17001a2c0>: pasin
2017-07-14 13:21:59.540943-0700 Todo[2187:570734] [Todo] Replicator: BUSY 0/0, error: (null)
2017-07-14 13:21:59.744015-0700 Todo[2187:570734] [Todo] Replicator: IDLE 0/0, error: (null)
```

**Comment by pasin** [comment]
This was fixed in LiteCore.

**Comment by tleyden** [comment]
I'm still seeing this, though not necessarily accompanied by any issues.

Versions:

- Couchbse-lite commit: https://github.com/couchbase/couchbase-lite-ios/commit/7f7c1e50904114817b97218f09b6f6062f121d65
- couchbase-lite-core: https://github.com/couchbase/couchbase-lite-core/commit/a6319c22567d5d62d3642ba132157ed254110aac
- couchbase-blip-cpp: https://github.com/couchbaselabs/BLIP-Cpp/commit/f13acc0a9628162f861c2ef29ea5d8ec49fffbdd

mobile-training-todo logs:

```
progress 482888/482890, error: (null)
2018-02-26 17:36:58.119912-0800 Todo[37738:7956764] [Todo] Replicator: 482888/482890, error: 
2018-02-26 17:36:58.119912-0800 Todo[37738:7993181] CouchbaseLite Sync Info: {Repl#9} now idle
2018-02-26 17:36:58.120432-0800 Todo[37738:7956764] CouchbaseLite Sync Info: CBLReplicator[<*> URL[ws://localhost:4984/todo]] is idle, progress 482888/482890, error: (null)
2018-02-26 17:36:58.120676-0800 Todo[37738:7956764] [Todo] Replicator: 482888/482890, error: 
2018-02-26 17:41:57.895306-0800 Todo[37738:7957767] CouchbaseLite WS Info: {C4SocketImpl#2}==> litecore::websocket::C4SocketImpl ws:localhost:4984/todo/_blipsync
2018-02-26 17:41:57.896133-0800 Todo[37738:7957767] CouchbaseLite WS Info: {C4SocketImpl#2} Sending PING
2018-02-26 17:41:57.896801-0800 Todo[37738:7957767] CouchbaseLite WS Verbose: >>> sending 6 bytes...
2018-02-26 17:41:57.899469-0800 Todo[37738:7993332] CouchbaseLite WS Verbose:     (...sent 6 bytes)
2018-02-26 17:41:57.899891-0800 Todo[37738:7993332] CouchbaseLite WS Verbose: <<< received 2 bytes [now 2 pending]
2018-02-26 17:41:57.900761-0800 Todo[37738:8011431] CouchbaseLite WS Info: {C4SocketImpl#2} Received PONG
2018-02-26 17:46:57.888062-0800 Todo[37738:7957767] CouchbaseLite WS Info: {C4SocketImpl#2} Sending PING
2018-02-26 17:46:57.888361-0800 Todo[37738:7957767] CouchbaseLite WS Verbose: >>> sending 6 bytes...
2018-02-26 17:46:57.889357-0800 Todo[37738:7993332] CouchbaseLite WS Info: CBLWebSocket CLOSED WITH ERROR: NSPOSIXError[60, "Operation timed out"]
2018-02-26 17:46:57.889849-0800 Todo[37738:7993332] CouchbaseLite WS WARNING: {C4SocketImpl#2} Unexpected or unclean socket disconnect! (reason=errno, code=60)
2018-02-26 17:46:57.890154-0800 Todo[37738:7993332] CouchbaseLite WS Info: {C4SocketImpl#2} sent 496 bytes, rcvd 959, in 600.013 sec (1/sec, 2/sec)
2018-02-26 17:46:57.890509-0800 Todo[37738:8030062] CouchbaseLite BLIP Info: {Connection#3} Closed with errno 60: Operation timed out
2018-02-26 17:46:57.890804-0800 Todo[37738:8030061] CouchbaseLite Sync Info: {Repl#9} Connection closed with errno 60: "Operation timed out" (state=2)
2018-02-26 17:46:57.891004-0800 Todo[37738:8030061] CouchbaseLite Sync ERROR: {Repl#9} Got LiteCore error: Operation timed out (2/60)
2018-02-26 17:46:57.891258-0800 Todo[37738:7993332] CouchbaseLite BLIP Info: {BLIPIO#4} ~BLIPIO: Sent 442 bytes, rcvd 937. Max outbox depth was 1, avg 1.00
2018-02-26 17:46:57.891854-0800 Todo[37738:8030061] CouchbaseLite Sync Verbose: {Repl#9} progress +0/+0, 0 docs -- now 482888 / 482890, 0 docs
2018-02-26 17:46:57.892096-0800 Todo[37738:8030061] CouchbaseLite Sync Info: {Repl#9} now stopped
2018-02-26 17:46:57.892620-0800 Todo[37738:8030061] CouchbaseLite DB Info: Closing DataFile
2018-02-26 17:46:57.893114-0800 Todo[37738:8030061] CouchbaseLite DB Verbose: Pre-close housekeeping: 0 of 11 pages free (0%)
2018-02-26 17:46:57.894325-0800 Todo[37738:7956764] CouchbaseLite Sync Info: CBLReplicator[<*> URL[ws://localhost:4984/todo]]: Transient error (Operation timed out); will retry in 2 sec...
```

mobile-training-todo full logs + SG logs:

https://gist.github.com/tleyden/e88a38c55f60d3bb5bfee337c3ac720b

**Comment by snej** [comment]
After 5 minutes of idle time LiteCore is sending a PING over the WebSocket, triggering an ETIMEDOUT error meaning that the write timed out. But it's weird that the error occurs only 1ms after the write...

**Comment by tleyden** [comment]
I’ll try to get a packet capture

**Comment by tleyden** [comment]
It looks like there might be a connection leak.

While looking at the wireshark trace to see what is happening during the time when the `NSPOSIXError[60, "Operation timed out"` message is being emitted,  it looks like the LiteCore side is opening a new connection.  

In packet no 5 at 2018-02-27 13:37:11.023:

![screen shot 2018-02-27 at 1 44 06 pm](https://user-images.githubusercontent.com/296876/36756802-ecab0a52-1bc4-11e8-97e1-5c32dd652c28.png)

which corresponds to approximately the time that the log line at `2018-02-27 13:37:08.984905-0800` is written:

```
2018-02-27 13:32:08.996020-0800 Todo[61139:9302291] CouchbaseLite WS Info: {C4SocketImpl#12}==> litecore::websocket::C4SocketImpl ws:localhost:4984/todo/_blipsync
2018-02-27 13:32:08.996216-0800 Todo[61139:9302291] CouchbaseLite WS Info: {C4SocketImpl#12} Sending PING
2018-02-27 13:32:08.996382-0800 Todo[61139:9302291] CouchbaseLite WS Verbose: >>> sending 6 bytes...
2018-02-27 13:32:08.996994-0800 Todo[61139:9729603] CouchbaseLite WS Verbose:     (...sent 6 bytes)
2018-02-27 13:32:08.997189-0800 Todo[61139:9729602] CouchbaseLite WS Verbose: <<< received 2 bytes [now 2 pending]
2018-02-27 13:32:08.997353-0800 Todo[61139:9729603] CouchbaseLite WS Info: {C4SocketImpl#12} Received PONG
---> 2018-02-27 13:37:08.984905-0800 Todo[61139:9716199] CouchbaseLite WS Info: CBLWebSocket CLOSED WITH ERROR: NSPOSIXError[60, "Operation timed out"]
2018-02-27 13:37:08.987022-0800 Todo[61139:9302291] CouchbaseLite WS Info: {C4SocketImpl#12} Sending PING
2018-02-27 13:37:08.987224-0800 Todo[61139:9302291] CouchbaseLite WS Verbose: >>> sending 6 bytes...
2018-02-27 13:37:08.989121-0800 Todo[61139:9716199] CouchbaseLite WS WARNING: {C4SocketImpl#12} Unexpected or unclean socket disconnect! (reason=errno, code=60)
2018-02-27 13:37:08.989935-0800 Todo[61139:9716199] CouchbaseLite WS Info: {C4SocketImpl#12} sent 496 bytes, rcvd 1013, in 600.016 sec (1/sec, 2/sec)
2018-02-27 13:37:08.990155-0800 Todo[61139:9749221] CouchbaseLite BLIP Info: {Connection#23} Closed with errno 60: Operation timed out
2018-02-27 13:37:08.990346-0800 Todo[61139:9749220] CouchbaseLite Sync Info: {Repl#89} Connection closed with errno 60: "Operation timed out" (state=2)
2018-02-27 13:37:08.990509-0800 Todo[61139:9749220] CouchbaseLite Sync ERROR: {Repl#89} Got LiteCore error: Operation timed out (2/60)
2018-02-27 13:37:08.990706-0800 Todo[61139:9716199] CouchbaseLite BLIP Info: {BLIPIO#24} ~BLIPIO: Sent 442 bytes, rcvd 991. Max outbox depth was 1, avg 1.00
2018-02-27 13:37:08.990854-0800 Todo[61139:9749220] CouchbaseLite Sync Verbose: {Repl#89} progress +0/+0, 0 docs -- now 482888 / 482890, 0 docs
2018-02-27 13:37:08.990994-0800 Todo[61139:9749220] CouchbaseLite Sync Info: {Repl#89} now stopped
2018-02-27 13:37:08.991306-0800 Todo[61139:9749220] CouchbaseLite DB Info: Closing DataFile
2018-02-27 13:37:08.996053-0800 Todo[61139:9749220] CouchbaseLite DB Verbose: Pre-close housekeeping: 0 of 11 pages free (0%)
2018-02-27 13:37:08.996880-0800 Todo[61139:9301843] CouchbaseLite Sync Info: CBLReplicator[<*> URL[ws://localhost:4984/todo]]: Transient error (Operation timed out); will retry in 2 sec...
2018-02-27 13:37:08.997057-0800 Todo[61139:9301843] CouchbaseLite Sync Info: CBLReplicator[<*> URL[ws://localhost:4984/todo]] is offline, progress 482888/482890, error: Error Domain=NSPOSIXErrorDomain Code=60 "Operation timed out" UserInfo={NSLocalizedDescription=Operation timed out}
2018-02-27 13:37:08.997256-0800 Todo[61139:9301843] [Todo] Replicator: 482888/482890, error: Error Domain=NSPOSIXErrorDomain Code=60 "Operation timed out" UserInfo={NSLocalizedDescription=Operation timed out}
2018-02-27 13:37:10.997032-0800 Todo[61139:9301843] CouchbaseLite Sync Info: CBLReplicator[<*> URL[ws://localhost:4984/todo]]: Retrying...
2018-02-27 13:37:10.999838-0800 Todo[61139:9301843] CouchbaseLite DB Info: Opening DataFile /Users/tleyden/Library/Developer/CoreSimulator/Devices/FD2A94F1-D45E-404E-812F-5C855E741313/data/Containers/Data/Application/AF4F1E29-84CC-4144-8BD6-C1E487ACDB0F/Library/Application Support/CouchbaseLite/user1.cblite2/db.sqlite3
2018-02-27 13:37:11.001218-0800 Todo[61139:9301843] CouchbaseLite BLIP Info: {Connection#25}==> litecore::blip::Connection ->ws:localhost:
```

[full logs](https://gist.github.com/tleyden/cc899574ab33907be264889f356d8191)

What makes it look like there might be a connection leak is that I'm not seeing the existing websocket connection getting closed.  Before the new connection is established, there is a PING/PONG sequence in packets 1-4 on port 55613.  If I check `netstat` for open sockets on that port, I see a connection with Sync Gateway:

```
$ netstat -an | grep -i 4984 | grep -i 55613
tcp6       0      0  ::1.4984               ::1.55613              ESTABLISHED
tcp6       0      0  ::1.55613              ::1.4984               ESTABLISHED
``` 

After 30+ minutes, that connection is still open.

I only have a single instance of mobile-training-todo connected to Sync Gateway, and I would expect it to only start one replicator.

This netstat output to track the connections w/ Sync Gateway shows the number of connections increasing, since the 2nd netstat output has 2 extra rows (one extra connection):

https://gist.github.com/tleyden/4e536e4d75f16e2e5afdea179607be54

The 3rd netstat output has 2 more rows than the previous output as well.  It also has a socket in the TIME_WAIT state, but that can be ignored because I can see from wireshark it's a socket that was created and then closed after calling `GET /todo/_blipsync` without the auth headers and getting a 401 Unauthorized response (it was then re-attempted and the 2nd time the auth headers were sent and the websocket was established)

Raw capture: 
[cblite_ios_1822.pcapng.gz](https://github.com/couchbase/couchbase-lite-ios/files/1764846/cblite_ios_1822.pcapng.gz)

Versions tested:

- Couchbse-lite commit: https://github.com/couchbase/couchbase-lite-ios/commit/7f7c1e50904114817b97218f09b6f6062f121d65
- couchbase-lite-core: https://github.com/couchbase/couchbase-lite-core/commit/a6319c22567d5d62d3642ba132157ed254110aac
- couchbase-blip-cpp: https://github.com/couchbaselabs/BLIP-Cpp/commit/f13acc0a9628162f861c2ef29ea5d8ec49fffbdd + cherry picked https://github.com/couchbaselabs/BLIP-Cpp/commit/f13acc0a9628162f861c2ef29ea5d8ec49fffbdd/dadd6437eb5ea931b131a425758b38f9f9aaa46a

**Comment by tleyden** [comment]
Was able to repro again with the latest version:

- Couchbse-lite commit: https://github.com/couchbase/couchbase-lite-ios/commit/44ca3f029d1b34e86a9b702963cd47fdd029b8ba
- couchbase-lite-core: https://github.com/couchbase/couchbase-lite-core/commit/7e38498720a52f96bb6b262c989e7dbd851afa01
- couchbase-blip-cpp: https://github.com/couchbaselabs/BLIP-Cpp/commit/a76c890789523fd09156b099f593fdcba941546a  (actually this isn't quite the latest, since the lite-core submodule doesn't point to https://github.com/couchbaselabs/BLIP-Cpp/commit/a4f2ad8858ada06fd0d69410daee01c6d4f222da yet)

**Comment by tleyden** [comment]
Based on these logs:

```
2018-02-27 11:31:46.228996-0800 Todo[61139:9301843] CouchbaseLite Sync Info: CBLReplicator[<*> URL[ws://localhost:4984/todo]]: Transient error (Operation timed out); will retry in 2 sec...
2018-02-27 11:31:46.229287-0800 Todo[61139:9301843] CouchbaseLite Sync Info: CBLReplicator[<*> URL[ws://localhost:4984/todo]] is offline, progress 484400/484402, error: Error Domain=NSPOSIXErrorDomain Code=60 "Operation timed out" UserInfo={NSLocalizedDescription=Operation timed out}
2018-02-27 11:31:46.229520-0800 Todo[61139:9301843] [Todo] Replicator: 484400/484402, error: Error Domain=NSPOSIXErrorDomain Code=60 "Operation timed out" UserInfo={NSLocalizedDescription=Operation timed out}
2018-02-27 11:31:48.229305-0800 Todo[61139:9301843] CouchbaseLite Sync Info: CBLReplicator[<*> URL[ws://localhost:4984/todo]]: Retrying...
2018-02-27 11:31:48.229845-0800 Todo[61139:9301843] CouchbaseLite DB Info: Opening DataFile /Users/tleyden/Library/Developer/CoreSimulator/Devices/FD2A94F1-D45E-404E-812F-5C855E741313/data/Containers/Data/Application/AF4F1E29-84CC-4144-8BD6-C1E487ACDB0F/Library/Application Support/CouchbaseLite/user1.cblite2/db.sqlite3
2018-02-27 11:31:48.230640-0800 Todo[61139:9301843] CouchbaseLite BLIP Info: {Connection#3}==> litecore::blip::Connection ->ws:localhost:4984/todo/_blipsync
2018-02-27 11:31:48.230793-0800 Todo[61139:9301843] CouchbaseLite BLIP Info: {Connection#3} Opening connection...

```

What looks like is happening is:

1. The CBL ios Replicator gets an error callback to `- (bool) handleError: (C4Error)c4err`: https://github.com/couchbase/couchbase-lite-ios/blob/6f5c2e511050819dd4178db9be6260be5bbade06/Objective-C/CBLReplicator.mm#L424
1. Calls retry: https://github.com/couchbase/couchbase-lite-ios/blob/6f5c2e511050819dd4178db9be6260be5bbade06/Objective-C/CBLReplicator.mm#L156
1. Calls start: https://github.com/couchbase/couchbase-lite-ios/blob/6f5c2e511050819dd4178db9be6260be5bbade06/Objective-C/CBLReplicator.mm#L169
1. Creates a new replicator: https://github.com/couchbase/couchbase-lite-ios/blob/6f5c2e511050819dd4178db9be6260be5bbade06/Objective-C/CBLReplicator.mm#L218 but leaves the previous one running, which would explain the increasing number of connections seen in `netstat`

**Comment by snej** [comment]
This didn't get reopened on the 26th, so I'm reopening now. Or has this been subsumed by #2708?

**Comment by snej** [comment]
Sounds like multiple CBLWebSockets are logging and getting mixed up with each other; that's why I thought the timeout was happening only 1ms after the write. 

To avoid this, the CBLWebSocket logs should include the identity of the C4Socket, i.e. they should use `%p` to print `_c4Socket`.

**Comment by tleyden** [comment]
Yeah, I filed https://github.com/couchbase/couchbase-lite-ios/issues/2078 to try to get a clearer description since this ticket is focused more around log messages rather than the potential resource leak.  I moved your comment over, sorry for the confusion!
