### ISSUE TITLE
Does not throw error with wrong blip protocol

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-ios#2119]
### Environment
* Version:   755
* Client OS: iOS
* Server:    sg - 823

### Steps to reproduce : 
1. Start the replication without blip protocol like http or other than 'ws' protocol.

### Result : 
1. It did not throw any error on cbl logs. 

### Expected : 
1. It should throw an error

### Note : 
It is happening only on iOS, Android and .net throws an error

**Comment by pasin** [comment]
Fixed in the master branch.

**Comment by pasin** [comment]
@sridevi-15 please confirm and close the issue if it has been fixed?

**Comment by sridevi-15** [comment]
@pasin , which build has this fix ? I tested on 806 and still seeing this issue

**Comment by pasin** [comment]
I see. There is a slightly implementation in Swift. It will through the exception when creating a replicator with the configuration.

**Comment by pasin** [comment]
Could you please test the fix with 2.1.0 Build 121?

**Comment by pasin** [comment]
I believe this is fixed. If the issue still happens, please reopen the issue again.
