### ISSUE TITLE
Attachment crash (CBL_BlobStoreWriter's initializer failed?)

### ISSUE THREAD

**Issue by nl** [couchbase/couchbase-lite-ios#649]
Commit b4850d3a1f4bd944eb9db8fe20fb4a409ebeff82
https://gist.github.com/nl/39b3d5b2bbbbd4533d71

**Comment by nl** [comment]
NB: The data I'm trying to attach is _NOT_ nil.

**Comment by snej** [comment]
```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', 
reason: '*** setObjectForKey: object cannot be nil (key: preview.jpg)'
terminating with uncaught exception of type NSException
abort() called
 
Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fff8456766c __exceptionPreprocess + 172
1   libobjc.A.dylib                     0x00007fff8d10b76e objc_exception_throw + 43
2   CoreFoundation                      0x00007fff8444f876 -[__NSDictionaryM setObject:forKey:] + 1174
3   CouchbaseLite                       0x000000010eff1e62 -[CBLMultipartDocumentReader startedPart:] + 391
4   CouchbaseLite                       0x000000010efeb90d -[CBLMultipartReader appendData:] + 800
5   CouchbaseLite                       0x000000010eff164c -[CBLMultipartDocumentReader appendData:] + 68
6   CouchbaseLite                       0x000000010f00b804 -[CBLBulkDownloader appendToPart:] + 58
7   CouchbaseLite                       0x000000010efeb521 -[CBLMultipartReader appendAndTrimBuffer] + 151
8   CouchbaseLite                       0x000000010efeba34 -[CBLMultipartReader appendData:] + 1095
9   CouchbaseLite                       0x000000010f00b572 -[CBLBulkDownloader connection:didReceiveData:] + 130
```

Looks like the line that triggered it is CBLMultipartDocumentReader.m:259; `_curAttachment` must be nil:
```objc
                _attachmentsByName[name] = _curAttachment;
```

**Comment by snej** [comment]
The only way for `_curAttachment` to be nil is if CBL_BlobStoreWriter's initializer failed and returned nil, and I think the only way for that to happen is if it can't create a temporary file.

Nico, is it possible that the device ran out of storage space?

**Comment by nl** [comment]
I checked the Mac this is running on, and the storage space is fine.

**Comment by snej** [comment]
Sorry, I keep forgetting you're writing a Mac app!

Looking at CBL_BlobStoreWriter's initializer, there seem to be only 3 possibilities:

* It was unable to create a temporary directory to put incoming attachments into. If this happened you'd have gotten a warning "`CBL_BlobStore: Unable to create temp dir:...`".
* It was unable to create an empty file in that directory. (Possibly a permissions error? But this would be down in `~/Library` so it's hard to see how it would get messed up.)
* It was unable to open the temporary file (maybe the process ran out of file handles? I know user processes used to get only 256, but I think that's been raised in recent OS versions.)

The code needs better error handling here so it can express what went wrong, and then not crash...

**Comment by snej** [comment]
Of those possibilities, I'm inclined to guess it's file handles. Maybe there's a leak. The `lsof` tool will show how many handles are open and what they connect to.

**Comment by nl** [comment]
Sounds possible. I see dozens/hundreds of entries just like
```
CouchbaseLite/user-cfecbe55-8d60-47f1-b721-e50e32331410.cblite2/attachments/9321B9D8B1DC9A1C9531C5624B12C541091FF4F7.blob
```

**Comment by snej** [comment]
You mean they show up in `lsof`? Hm, that's not good.
Is your app opening attachment streams directly? (Calling -[CBLAttachment openContentStream] ?)

**Comment by nl** [comment]
Nope, just getting the attachment via -[CBLModel attachmentNamed:], then its data via attachment.content

**Comment by nl** [comment]
(The app is using sandboxing, if that changes anything.)

**Comment by pasin** [comment]
I couldn't reproduce this myself. Below is what I found so far after looking at the issue:

1. Memory leak due to a circle reference between CBLUnsavedRevision and CBLAttachment. CBLAttachment has a retained revision property which doesn't currently get used by any codes. However this doesn't seem to a root cause of file descriptor leaking.

2. When a pusher calls uploadMultipartRevision, there could be multiple attachment content stream added to the CBLMultipartWriter. And if the encoding is kCBLAttachmentEncodingNone, the added stream will be opened before it is added to the writer (https://github.com/couchbase/couchbase-lite-ios/blob/bbd3b72649634388a3a881edbfc7336bfff7d15e/Source/CBL_BlobStore.m#L151-L152). In theory, if CBLMultipartWriter operation is not complete for some reason, the opened stream will not get closed.

3. From @nl comment about the result of lsof, the left open descriptor are .blob file descriptors not the .blobtmp ones so the file descriptors opened by CBL_BlobStoreWriter are not leaking. (@nl could you confirm that there is no .blobtmp?)

**Comment by nl** [comment]
I confirm there are definitely no .blobtmp.
https://gist.github.com/nl/2f452c6b890f0963a0ff

**Comment by pasin** [comment]
@nl Thanks for confirming that.

**Comment by snej** [comment]
The .blobtmp files get moved into the main attachment directory and renamed to end with .blob. So these could be incoming attachments. I think they probably are, because once they're added, the attachment files don't get explicitly opened as file handles unless the client calls CBLAttachment.openInputStream.

**Comment by pasin** [comment]
I barely saw file descriptors opened during the pull operations but I did see several thousand descriptors opened when I tested pushing 5000 attachments. Did the crash happen during pushing high volume of docs with attachments?

**Comment by pasin** [comment]
@nl do you mind checkout `feature/issue_649_file_handlers` branch and see if it helps? 

I don't know if this is the issue that you are facing or not but the fix minimizes significant # of opened file descriptors during large push of attachments.

**Comment by nl** [comment]
The new branch did not change the lsof output for me. However, I moved away from using attachment.content and am now using attachment.contentURL and it did the trick.

Before (BAD, tons of attachment file handles open in lsof):
	NSData *data = attachment.content;
	if (!data) return nil;
	return [[NSImage alloc] initWithData:data];

After (GOOD, no CouchbaseLite file handles in lsof except de db):
	NSURL *dataURL = attachment.contentURL;
	if (!dataURL) return nil;
	return [[NSImage alloc] initWithContentsOfURL: dataURL];

**Comment by nl** [comment]
I am however getting an assertion failure in -[CBLBulkDownloader startedPart:]

```
0   CoreFoundation                      0x00007fff8456766c __exceptionPreprocess + 172
1   libobjc.A.dylib                     0x00007fff8d10b76e objc_exception_throw + 43
2   CoreFoundation                      0x00007fff8456744a +[NSException raise:format:arguments:] + 106
3   Foundation                          0x00007fff8ef44471 -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] + 169
4   CouchbaseLite                       0x000000010e9a9cdd _AssertFailed + 749
5   CouchbaseLite                       0x000000010e96140e -[CBLBulkDownloader startedPart:] + 126
6   CouchbaseLite                       0x000000010e92afa2 -[CBLMultipartReader appendData:] + 2018
7   CouchbaseLite                       0x000000010e961193 -[CBLBulkDownloader connection:didReceiveData:] + 147
8   CFNetwork                           0x00007fff82e9720d __65-[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:]_block_invoke + 69
9   CFNetwork                           0x00007fff82e971b1 -[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:] + 232
10  CFNetwork                           0x00007fff82e97317 -[NSURLConnectionInternal _withActiveConnectionAndDelegate:] + 48
11  CFNetwork                           0x00007fff82e7d789 _ZL30_NSURLConnectionDidReceiveDataP16_CFURLConnectionPK8__CFDatalPKv + 79
```

**Comment by snej** [comment]
The code behind CBLAttachment.content is reading NSData from the file with the option NSDataReadingMappedIfSafe … that's good if the file is large, but it does associate a file handle with the data, so if the NSData object stays around the file stays open, and if you get a lot of attachments and keep the data objects around, it might cause your problem.

Fix would be to take that option out of -[CBL_BlobStore blobForKey:].

**Comment by pasin** [comment]
@nl I believe we fixed your issue. Could you update your code and see if the problem is gone?

**Comment by nl** [comment]
The symptoms are now slightly different but the problem is still there.
```
WARNING: CBL_BlobStore: Unable to create temp dir: Error Domain=NSCocoaErrorDomain Code=512 "The file couldn’t be saved."
```

https://gist.github.com/nl/da54ccc390f2cfcce102

This is ``df -k`` on the machine. https://gist.github.com/nl/dc59a0ebc8bd2af0edb8

**Comment by pasin** [comment]
Can you also post the log message showing the parent path and the tmp folder that the blob store tried to create? I didn't see it in your gist as well. It should be above the WARNING message.

```
https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/CBL_BlobStore.m#L272
```

Anyway, not quite sure why it couldn't create the temp folder. Reopen the issue.

**Comment by nl** [comment]
The gist is everything I have in stdout.

**Comment by pasin** [comment]
Can you enable Log? There are 2 ways to enable the Log.

1. Add a boolean user default also called Log.
2. Add '-Log YES' to the "Arguments Passed On Launch" list.

Full Description: https://github.com/couchbase/couchbase-lite-ios/wiki/Logging.

First we would like to check what the parent and temp folder are and also see if the parent folder exists or not.

**Comment by nl** [comment]
I guess this is it?

```
01:03:54.433| CBL_BlobStore /Users/nico/Library/Application Support/com.torrentsapp.Torrents-Core/CouchbaseLite/user-admin.cblite2/attachments created tempDir (null)
01:03:54.433| WARNING: CBL_BlobStore: Unable to create temp dir: Error Domain=NSCocoaErrorDomain Code=512 "The file couldn’t be saved."
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by pasin** [comment]
Thanks for the log message. 
Can you help confirming if "/Users/nico/Library/Application Support/com.torrentsapp.Torrents-Core/CouchbaseLite/user-admin.cblite2/attachments" folder exists?

**Comment by nl** [comment]
Yes, it exists.

**Comment by pasin** [comment]
I tested both sandbox and non-sandbox mode replicating 5000 docs with attachments but I couldn't reproduce the issue. I don't know about sandbox restriction that much so I don't know if it has any restriction regarding temporary directory or not.

One thing that I noticed is that for Mac parent url and the temp director returned by the NSFileManager's URLForDirectory method are not related to each other. For example, 

Parent: 
```
/Users/pasin/Library/Containers/com.couchbase.TestMac2/Data/Library/Application Support/com.couchbase.TestMac2/CouchbaseLite/db.cblite2/attachments created tempDir 
```
Temp Dir:
```
/private/var/folders/8d/dtkmgqg51f77g_1qg1w0lz7w0000gn/T/com.couchbase.TestMac2/TemporaryItems/(A Document Being Saved By TestMac2 6)
```

**Comment by pasin** [comment]
One thing that we can quickly try is to use NSTemporaryDirectory() instead of NSFileManager to get the temp directory for Mac. I made a quick change and made a branch. 

@nl, Could you checkout `feature/issue_649_tempdir` branch and see if it helps? Please let me know.

**Comment by zgramana** [comment]
Didn't make the cutoff for 1.1, so moving to 1.2.

**Comment by nl** [comment]
@pasin I have updated the framework and the issue hasn't happened since. I think the temp directory thing fixed it. I have no clue why, though.

**Comment by pasin** [comment]
@nl , do you mean 'feature/issue_649_tempdir' fixes the issue? or Do you mean updating the framework from the current master fixes the issue?

**Comment by pasin** [comment]
@nl I understand that there is nothing to fix. I'm closing the issue now. Please reopen the issue if otherwise.

**Comment by DharmenderYadav** [comment]
WARNING: CBL_BlobStoreWriter can't create temp file at /private/var/mobile/Containers/Data/Application/A7FA6AD1-E978-40A4-A0CF-CCDADD69D873/tmp/(A Document Being Saved By TestApp)/-wdgHm4AFztOTITG2R4lsMr.blobtmp (errno 2)
2016-07-20 12:10:24.037 TestApp[5315:2354805] WARNING: Exception caught in CBLDatabase transaction:
	*** -[__NSDictionaryM removeObjectForKey:]: key cannot be nil
	0   CoreFoundation                      0x0000000180cf1918 <redacted> + 148
	2   CoreFoundation                      0x0000000180bf962c <redacted> + 708
	3   TestApp                                0x00000001003d40cc MYSliceReadVarUInt + 32544
	4   TestApp                                0x00000001003fa50c CBLGeoJSONBoundingBox + 6916
	5   TestApp                                0x000000010040cad4 cfSetObj + 3388
	6   CoreFoundation                      0x0000000180bdd6d8 <redacted> + 120
	7   CoreFoundation                      0x0000000180bdd5b0 <redacted> + 180
	8   TestApp                                0x000000010040c9fc cfSetObj + 3172
	9   TestApp                                0x00000001003fa2cc CBLGeoJSONBoundingBox + 6340
	10  TestApp                                0x00000001003df47c CBLCheckSSLServerTrust + 7772
	11  TestApp                                0x00000001003e34cc CBLCheckSSLServerTrust + 24236
	12  TestApp                                0x0000000100353ef8 _TFC4TestApp14BaseRepository28createDocumentWithPropertiesfTGSqSS_10propertiesGVs10DictionarySSPs9AnyObject__11attachmentsGSqGS1_SSSS___GSqCSo16CBLSavedRevision_ + 2244
	13  TestApp                                0x00000001002b3230 _TFC4TestApp19AssetDataRepository11insertAssetfTGSqSS_9assetDataCS_9AssetData11attachmentsGSqGVs10DictionarySSSS___GSqSS_ + 492
	14  TestApp                                0x00000001001cdb18 _TFC4TestApp15FormDataStorageP33_7DE220F0310344B59BD54CB2C3A0681811insertAssetfTCS_9AssetData10assestInfoGVs10DictionarySSPs9AnyObject___GSqSS_ + 1884
	15  TestApp                                0x00000001001ccdcc _TFC4TestApp15FormDataStorageP33_7DE220F0310344B59BD54CB2C3A0681812insertAssetsfTCS_12FormResponse15preFormResModelGSqS1__8parentIdSS_GSqGSaSS__ + 3132

**Comment by snej** [comment]
@DharmenderYadav Please file a new bug instead of commenting on an old closed one.
